version: '2.1'
services:
  activemq:
    container_name: activemq
    image: webcenter/activemq:latest
    ports:
      - "8161:8161"
      - "61616:61616"
    expose:
      - "8161"
      - "61616"
      - "61613"
  producer:
    container_name: producer
    image: dmunozr/camel-activemq-producer:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      activemq:
        condition: service_started
  consumer:
    container_name: consumer
    build:
      context: ./consumer
    ports:
      - "8081:8080"
      - "5006:5005"
    depends_on:
      activemq:
        condition: service_started
  final-consumer:
    container_name: final-consumer
    build:
      context: ./final-consumer
    ports:
      - "8082:8080"
      - "5007:5005"
    environment:
      - CAR_BRAND=peugeot,ford
      - CONTAINER_NAME=final-consumer-1
    depends_on:
      activemq:
        condition: service_started
